apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app.kubernetes.io/name: hellok8s
    app.kubernetes.io/component: backend
spec:

  ports:
  - port: 6379
  selector:
    app.kubernetes.io/name: hellok8s
    app.kubernetes.io/component: backend

