apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: backend
  labels:
    app.kubernetes.io/name: hellok8s
    app.kubernetes.io/component: backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hellok8s
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hellok8s
        app.kubernetes.io/component: backend
    spec:
      containers:
      - name: backend
        image: redis

        ports:
        - containerPort: 6379

