apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: hellok8s
    app.kubernetes.io/component: frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hellok8s
      app.kubernetes.io/component: frontend
#  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hellok8s
        app.kubernetes.io/component: frontend
    spec:
      containers:
      - name: hellok8s
        image: bennyrochwerger/helloworld:1.3

        env:
        - name: NAME
          value: "John Doe"

        - name: BE_HOST
          value: "backend"

        - name: COUNTER
          value: "VISITS"

        ports:
        - containerPort: 5000

#        imagePullPolicy: Always
