apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: hellok8s
    app.kubernetes.io/component: frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: hellok8s
      app.kubernetes.io/component: frontend
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hellok8s
        app.kubernetes.io/component: frontend
    spec:
      containers:
      - name: hellok8s
        image: bennyrochwerger/helloworld:1.2
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
#        env:
#        - name: GET_HOSTS_FROM
#          value: dns
        ports:
        - containerPort: 5000

